
export const SAVE_TOKENS_CONSTANT = {
  ACCESS_TOKEN: '@ACCESS_TOKEN',
  REFRESH_TOKEN: '@REFRESH_TOKEN',
};
export const USER_AUTH = '@userauth';

export const typeConstants = {
  // ── Auth ──
  LOGIN: 'LOGIN',
  CHECK_AUTH: 'CHECK_AUTH',
  LOGOUT_AUTH: 'LOGOUT_AUTH',

  // ── Dashboard ──
  GET_DASHBOARD: 'GET_DASHBOARD',

  // ── Agents ──
  GET_AGENTS: 'GET_AGENTS',
  GET_AGENT_BY_ID: 'GET_AGENT_BY_ID',
  UPDATE_AGENT_STATUS: 'UPDATE_AGENT_STATUS',
  VERIFY_AGENT: 'VERIFY_AGENT',
  SUSPEND_AGENT: 'SUSPEND_AGENT',
  CREATE_AGENT: 'CREATE_AGENT',
  UPDATE_AGENT: 'UPDATE_AGENT',
  DELETE_AGENT: 'DELETE_AGENT',

  // ── Clients ──
  GET_CLIENTS: 'GET_CLIENTS',
  GET_CLIENT_BY_ID: 'GET_CLIENT_BY_ID',
  UPDATE_CLIENT_STATUS: 'UPDATE_CLIENT_STATUS',
  SUSPEND_CLIENT: 'SUSPEND_CLIENT',
  CREATE_CLIENT: 'CREATE_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',

  // ── Users ──
  GET_USERS: 'GET_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // ── Quiz Categories ──
  GET_CATEGORIES: 'GET_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  // ── Quiz Questions ──
  GET_QUESTIONS: 'GET_QUESTIONS',
  CREATE_QUESTION: 'CREATE_QUESTION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',

  // ── Matches ──
  GET_MATCHES: 'GET_MATCHES',
  GET_MATCH_BY_ID: 'GET_MATCH_BY_ID',
  UPDATE_MATCH_STATUS: 'UPDATE_MATCH_STATUS',

  // ── Messages ──
  GET_CONVERSATIONS: 'GET_CONVERSATIONS',
  GET_CHAT_MESSAGES: 'GET_CHAT_MESSAGES',
  SEND_MESSAGE: 'SEND_MESSAGE',
  TOGGLE_USER_STATUS:'TOGGLE_USER_STATUS'
};

// Default placeholder image for profile pictures
export const DEFAULT_PROFILE_IMAGE =
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTARHCPrgly9x-1TlRPk2jQhRYZ3SrWEnp-cA&s';
