
export const SAVE_TOKENS_CONSTANT = {
  ACCESS_TOKEN: '@ACCESS_TOKEN',
  REFRESH_TOKEN: '@REFRESH_TOKEN',
};
export const USER_AUTH = '@userauth';

export const typeConstants = {
  // ── Auth ──
  LOGIN: 'LOGIN',
  CHECK_AUTH: 'CHECK_AUTH',
  LOGOUT_AUTH: 'LOGOUT_AUTH',

  // ── Dashboard ──
  GET_DASHBOARD: 'GET_DASHBOARD',

  // ── Users ──
  GET_EMPLOYERS: 'GET_EMPLOYERS',
  GET_SINGLE_EMPLOYER: 'GET_SINGLE_EMPLOYER',
  CREATE_EMPLOYER: 'CREATE_EMPLOYER',
  UPDATE_EMPLOYER: 'UPDATE_EMPLOYER',
  DELETE_EMPLOYER: 'DELETE_EMPLOYER',

  GET_SALARY_SLIPS: "GET_SALARY_SLIPS",
  GET_SINGLE_SALARY_SLIP: "GET_SINGLE_SALARY_SLIP",


  // FACTROY WORK
  GET_FACTORY_WORK: "GET_FACTORY_WORK",
  GET_SINGLE_FACTORY_WORK: "GET_SINGLE_FACTORY_WORK",
  CREATE_FACTORY_WORK: "CREATE_FACTORY_WORK",
  UPDATE_FACTORY_WORK: "UPDATE_FACTORY_WORK",
  DELETE_FACTORY_WORK: "DELETE_FACTORY_WORK",
  CREATE_FACTORY_PAYMENT: "CREATE_FACTORY_PAYMENT",
  UPDATE_MATERIAL_MOVEMENT: "UPDATE_MATERIAL_MOVEMENT",
  UPDATE_SITE_ARRIVAL: "UPDATE_SITE_ARRIVAL",
  SET_VEHICAL_INFO: "SET_VEHICAL_INFO",
  CREATE_VEHICAL_PAYMENT: "CREATE_VEHICAL_PAYMENT",
  DELETE_FACTORY_WORK: "DELETE_FACTORY_WORK",
};
